#################################################################
#                                                               #
#                   Packages/Xiaomi Status                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  #customize:

  
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  xiaomi_door_sensors:
    name: Door Sensors
    view: no
    entities:
      - binary_sensor.front_door
      - binary_sensor.balcony_door

  xiaomi_motion_sensors:
    name: Motion Sensors
    view: no
    entities:
      - binary_sensor.motion_shower
      - binary_sensor.motion_sensor_158d000204bfcb
      - binary_sensor.motion_sensor_158d0002b42fa3
      - binary_sensor.motion_sensor_158d00024e7972

  xiaomi_temperature_sensors:
    name: Temperature Sensors
    view: no
    entities:
      - sensor.temperature_158d00022ece24
      - sensor.second_floor_temperature

      
#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:
  - platform: template
    sensors:
## Door Sensors
      front_door:
        friendly_name: Front Door Sensor
        device_class: connectivity
        entity_id: sensor.front_door
        value_template: "{{ is_state('binary_sensor.front_door', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.front_door', 'on') %}
            fas:door-open
          {% elif is_state('binary_sensor.front_door', 'off') %}
            fas:door-closed         
          {% else %}
            mdi:alert
          {% endif %}
          
      balcony_door:
        friendly_name: Exit Door to balcony
        device_class: connectivity
        entity_id: binary_sensor.balcony_door
        value_template: "{{ is_state('binary_sensor.balcony_door', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.balcony_door', 'on') %}
            fas:door-closed
          {% elif is_state('binary_sensor.balcony_door', 'off') %}
            fas:door-open         
          {% else %}
            mdi:alert
          {% endif %}

## Motion Sensors
      motion_shower:
        friendly_name: Motion sensor Main Shower
        device_class: connectivity
        entity_id: binary_sensor.motion_shower
        value_template: "{{ is_state('binary_sensor.motion_shower', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.motion_shower', 'on') %}
            mdi:walk
          {% elif is_state('binary_sensor.motion_shower', 'off') %}
            mdi:walk         
          {% else %}
            mdi:alert
          {% endif %}

      bedroom_motion:
        friendly_name: Bedroom sensor
        device_class: connectivity
        entity_id: binary_sensor.motion_sensor_158d000204bfcb
        value_template: "{{ is_state('binary_sensor.motion_sensor_158d000204bfcb', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.motion_sensor_158d000204bfcb', 'on') %}
            mdi:walk
          {% elif is_state('binary_sensor.motion_sensor_158d000204bfcb', 'off') %}
            mdi:walk        
          {% else %}
            mdi:alert
          {% endif %}

      guest_services:
        friendly_name: Guest Services Motion Sensor
        device_class: connectivity
        entity_id: binary_sensor.motion_sensor_158d0002b42fa3
        value_template: "{{ is_state('binary_sensor.motion_sensor_158d0002b42fa3', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.motion_sensor_158d0002b42fa3', 'on') %}
            mdi:walk
          {% elif is_state('binary_sensor.motion_sensor_158d0002b42fa3', 'off') %}
            mdi:walk         
          {% else %}
            mdi:alert
          {% endif %} 
          
          
      computer_room:
        friendly_name: Motion Sensor Computer Room
        device_class: connectivity
        entity_id: binary_sensor.motion_sensor_158d000272bc63
        value_template: "{{ is_state('binary_sensor.motion_sensor_158d000272bc63', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.motion_sensor_158d000272bc63', 'on') %}
            mdi:walk
          {% elif is_state('binary_sensor.motion_sensor_158d000272bc63', 'off') %}
            mdi:walk         
          {% else %}
            mdi:alert
          {% endif %} 

      laundry_room:
        friendly_name: Motion Sensor Laundry Room
        device_class: connectivity
        entity_id: binary_sensor.motion_sensor_158d00024e7972
        value_template: "{{ is_state('binary_sensor.motion_sensor_158d00024e7972', 'on') }}"
        icon_template: >-
          {% if is_state('binary_sensor.motion_sensor_158d00024e7972', 'on') %}
            mdi:walk
          {% elif is_state('binary_sensor.motion_sensor_158d00024e7972', 'off') %}
            mdi:walk         
          {% else %}
            mdi:alert
          {% endif %} 


## Temerature Sensors
      computer_temperature:
        friendly_name: "Computer Room Temperature"
        value_template: >-
          {% if is_state('sensor.temperature_158d00022ece24', 'unavailable') %}
            off
          {% else %}
            on
          {% endif %}
      second_temperature:
        friendly_name: "Second Floor Temperature"
        value_template: >-
          {% if is_state('sensor.second_floor_temperature', 'unavailable') %}
            off
          {% else %}
            on
          {% endif %}