#################################################################
#                                                               #
#                      Packages/Firmware                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  firmware:
    name: Firmware Status
    view: no
    entities:
      - binary_sensor.new_podcast_available
      - binary_sensor.ha_update_available
      - binary_sensor.new_routeros_available
      - binary_sensor.sonoff_update_available
      
#################################################################
#                                                               #
#                        Input Boolean                          #
#                                                               #
#################################################################

input_boolean:        
  ha_update_available:
    name: HA Update Avaiable
    initial: off
    icon: mdi:cloud-download
    
  new_podcast_available:
    name: New Podcast Avaiable
    initial: off
    icon: mdi:podcast
    
  sonoff_update_available:
    name: Sonoff Update Avaiable
    initial: off
    icon: mdi:lightbulb-on

  new_routeros_available:
    name: RouterOS Update Avaiable
    initial: off
    icon: mdi:router-wireless
    
#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                  Latest HA Version               #
#                                                  #
####################################################

## Check Latest HA Version
  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/stable.json
    name: Latest HA Version
    value_template: "{{ value_json.homeassistant.default }}"
    scan_interval: 3600

####################################################
#                                                  #
#                    HA Podcast                    #
#                                                  #
####################################################

## Check Latest HA Podcast
  - platform: scrape
    resource: https://hasspodcast.io/feed/podcast
    name: Latest HA Podcast
    select: 'enclosure:nth-of-type(1)'
    value_template: '{{ value.split("/")[7] }}'
    attribute: url
