#################################################################
#                                                               #
#                       Packages/Electricity                    #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.phaze_1_total:
      friendly_name: שימוש כללי
      icon: mdi:power-cycle
    
    sensor.phaze_1_current:  
      friendly_name: צריכה
      icon: mdi:chart-line-variant
    
    sensor.phaze_1_today:
      friendly_name: שימוש יומי
      icon: mdi:calendar-today
      
    sensor.phaze_1_yesterday:
      friendly_name: שימוש בעבר
      icon: mdi:calendar-blank
    
    sensor.phaze_1_voltage:
      friendly_name: מתח
      icon: mdi:battery-charging-outline

    sensor.phaze_1_power_factor:
      friendly_name: הפרש הספק
      icon: mdi:altimeter
    
    sensor.power_calc_total_phaze1:  
      icon: fas:bolt
      
    sensor.power_calc_today_phaze1:
      icon: mdi:cash
    
    sensor.power_calc_yesterday_phaze1:
      icon: mdi:cash-usd

    sensor.phaze_1_power:
      friendly_name: הספק      

    sensor.phaze_1_reactive_power:
      friendly_name: צריכה תגובתית      

    sensor.phaze_1_apparent_power:
      friendly_name: צריכה הסתברותית
      


      
 
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
################################################################# 
      
group:
  money:
    name: Total Money
    view: no
    entities:
      - sensor.power_calc_total_phaze1 
      - sensor.power_calc_today_phaze1
      - sensor.power_calc_yesterday_phaze1

  power consumption:
    name: Electricity
    view: no
    entities:
      - sensor.phaze_1_total
      - sensor.phaze_1_current
      - sensor.phaze_1_today
      - sensor.phaze_1_yesterday

  voltage:
    name: All Voltage
    view: no
    entities:
      - sensor.phaze_1_voltage
      - sensor.phaze_1_yesterday
      - sensor.phaze_1_power_factor
      - sensor.phaze_1_apparent_power
      - sensor.phaze_1_reactive_power

  electric clock:
    name: Electric Company
    view: no
    entities:
      - input_number.kwh_number
      - input_number.shekel_number
      - sensor.kwh_count_all
      - sensor.kwh_count_yesterday

#################################################################
#                                                               #
#                          input number                         #
#                                                               #
#################################################################
input_number:
  kwh_number:
    name: kWh Count
    initial: 27210
    min: 0
    max: 999999999
    step: 1
    mode: box 

  shekel_number:
    name: shekel Count
    # initial: 806
    min: 0
    max: 999999999
    step: 1
    mode: box      

#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 

sensor:
  - platform: mqtt
    name: "Phaze 1 - Voltage"
    state_topic: "tele/electricity/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Phaze 1 - Current"
    state_topic: "tele/electricity/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"
  - platform: mqtt
    name: "Phaze 1 - Power"
    state_topic: "tele/electricity/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Phaze 1 - Power Factor"
    state_topic: "tele/electricity/SENSOR"
    value_template: "{{ value_json['ENERGY'].Period }}"
    unit_of_measurement: "PF"
  - platform: mqtt
    name: "Phaze 1 - Today"
    state_topic: "tele/electricity/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Phaze 1 - Yesterday"
    state_topic: "tele/electricity/SENSOR"
    value_template: "{{ value_json['ENERGY'].Yesterday }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Phaze 1 - Total"
    state_topic: "tele/electricity/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh" 
  - platform: mqtt
    name: "Phaze 1 - Apparent Power"
    state_topic: "tele/electricity/SENSOR"
    value_template: "{{ value_json['ENERGY'].ApparentPower }}"
    unit_of_measurement: "VA"
  - platform: mqtt
    name: "Phaze 1 - Reactive Power"
    state_topic: "tele/electricity/SENSOR"
    value_template: "{{ value_json['ENERGY'].ReactivePower }}"
    unit_of_measurement: "VAr"   


#################################################################
#                          Tami 4                               #
#################################################################     
  - platform: mqtt
    name: "BlitzWolf shp1 energy today"
    state_topic: "tele/bw-shp1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "BlitzWolf shp1 yesterday"
    state_topic: "tele/bw-shp1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "BlitzWolf shp1 total"
    state_topic: "tele/bw-shp1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "BlitzWolf shp1 total cost"
    state_topic: "tele/bw-shp1/SENSOR"
    value_template: '{{ (value_json["ENERGY"]["Total"] * 0.5404) | round(3) }}'
    #ILS OR USD (Depends on local currency) Just change the value of "0.5404" to your local elctricity price
    unit_of_measurement: "₪" # USD / Other local currency 

  - platform: template
    sensors:
      power_calc_total_phaze1:
        friendly_name: "חישוב צריכה כללי"
        value_template: "{{(((states.sensor.phaze_1_total.state | float) * 54.04) / 100) | round(2) }}"
        unit_of_measurement: "₪"
      power_calc_today_phaze1:
        friendly_name: "חישוב צריכה יומית"
        value_template: "{{(((states.sensor.phaze_1_today.state | float) * 54.04) / 100) | round(2) }}"
        unit_of_measurement: "₪"
      power_calc_yesterday_phaze1:
        friendly_name: "חישוב צריכה יום קודם"
        value_template: "{{(((states.sensor.phaze_1_yesterday.state | float) * 54.04) / 100) | round(2) }}"
        unit_of_measurement: "₪" 

      kwh_count_all:
        friendly_name: "KWH Count Total"
        value_template: "{{((states.input_number.kwh_number.state | float) + (states.sensor.phaze_1_total.state | float)) | round(2) }}"
        unit_of_measurement: "kWh"
      shekel_count_all:
        friendly_name: "shekel Count start"
        value_template: "{{((states.input_number.shekel_number.state | float) + (states.sensor.power_calc_yesterday_phaze1.state | float)) | round(2) }}"
        unit_of_measurement: "₪"        
      kwh_count_yesterday:
        friendly_name: "KWH Count Yesterday"
        value_template: "{{((states.sensor.kwh_count_all.state | float) - (states.sensor.phaze_1_yesterday.state | float)) | round(2) }}"
        unit_of_measurement: "kWh"        
       

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
automation:
  - alias: Set shekel_number
    initial_state: 'on'
    trigger:
      platform: time
      at: '03:14:00'

    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.shekel_number
        value: "{{ states.sensor.shekel_count_all.state | float }}"