#################################################################
#                                                               #
#                       Packages/Presence                       #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    device_tracker.nurit_iphone:
      friendly_name: מצב הסוללה
      
    device_tracker.iphone_nurit:
      friendly_name: נורית 
      entity_picture: /local/known_devices/nurit.png


    device_tracker.avi_note8:
      friendly_name: אבי 
      entity_picture: /local/known_devices/avi.png
      
    sensor.next_bus:
      icon: 'mdi:bus-clock'      
 
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
################################################################# 
      
group:
  people at home:
    name: People
    view: no
    entities:
      - device_tracker.avi_note8
      # - device_tracker.iphone_nurit
      - sensor.avi_battery
      # - sensor.nurit_iphone_battery_level


    
#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 

sensor:
  # Zanzito #
  - platform: mqtt
    state_topic: "owntracks/Avi/avi"
    name: "Avi Battery"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    device_class: battery


  - platform: template
    sensors:
      next_bus:
        friendly_name: Time to Next Bus
        unit_of_measurement: min
        value_template: >
          {% set min_now = states('sensor.time').split(':')[1]|int %}
          {% set time_now_h = states('sensor.time').split(":",)[0].replace("0", "")|int %}
          {% set time_now_m = states('sensor.time').split(":",)[1].replace("0", "")|int %}
          {% if now().strftime("%H")|int < 5 %}
            {{ (330 - (time_now_h*60) + (time_now_m)) }}
          {% elif now().strftime("%H")|int < 6 %}
            {{ 29 - min_now if min_now < 29 else 59 - min_now if min_now < 59 }}
          {% elif now().strftime("%H")|int < 7 %}
            {{ 19 - min_now if min_now < 19 else 39 - min_now if min_now < 39 else 59 - min_now if min_now < 59 }}
          {% elif now().strftime("%H")|int < 8 %}
            {{ 14 - min_now if min_now < 14 else 29 - min_now if min_now < 29 else 44 - min_now if min_now < 44 else 59 - min_now if min_now < 59 }}
          {% elif now().strftime("%H")|int < 9 %}
            {{ 14 - min_now if min_now < 9 else 29 - min_now if min_now < 29 else 49 - min_now if min_now < 49 }}
          {% elif now().strftime("%H")|int < 15 %}
            {{ 9 - min_now if min_now < 9 else 29 - min_now if min_now < 29 else 49 - min_now if min_now < 49 }}
          {% elif now().strftime("%H")|int < 18 %}
            {{ 14 - min_now if min_now < 14 else 24 - min_now if min_now < 24 else 39 - min_now if min_now < 39 else 54 - min_now if min_now < 54 }}
          {% elif now().strftime("%H")|int < 20 %}
            {{ 14 - min_now if min_now < 9 else 34 - min_now if min_now < 34 else 59 - min_now if min_now < 59 }}
          {% elif now().strftime("%H")|int < 24 %}
            {{ 29 - min_now if min_now < 29 else 59 - min_now if min_now < 59 }}
          {% else %}
            Unknown
          {% endif %}            
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
automation:
###########################
  - alias:  turn off xiaomi cameras if avi at home
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.avi_note8
      to: 'home'
      for:
        minutes: 1
        seconds: 30
    action:
      - service: homeassistant.turn_off
        entity_id: switch.sh20_pow 

      - service: notify.avitelegram
        data:
          title: "אבטחה"
          message: 'ברוך הבא אבי, המצלמה כבויה' 

########################### 
  - alias:  turn off xiaomi cameras if nurit at home
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.iphone_nurit
      to: 'home'
      for:
        minutes: 1
        seconds: 30
    action:
      - service: homeassistant.turn_off
        entity_id: switch.sh20_pow 

      - service: notify.iphone_nurit
        data:
          title: "אבטחה"
          message: 'ברוכה הבאה נורית, המצלמה כבויה'
          data:
            push:
              sound: "US-EN-Alexa-Welcome-Home.wav"
              badge: 0
              category: 'modifymycctvswitch'
            attachment: 
              url: https://cdn2.iconfinder.com/data/icons/forbidden-signs/512/forbidden_record_video-512.png
              
              
########################## 
  - alias:  turn OFF xiaomi cameras if Morning and we are at home
    initial_state: 'on'
    trigger:
      platform: time
      at: '07:00:00'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: device_tracker.avi_note8
          state: 'home'
        - condition: state
          entity_id: notify.iphone_nurit
          state: 'home'

    action:
      - service: homeassistant.turn_off
        entity_id: switch.sh20_pow
      - service: notify.avitelegram
        data:
          title: "אבטחה"
          message: 'אתם בבית - המצלמה נסגרה, אין צורך '        
          

          
##########################          
  - alias:  turn on xiaomi cameras if nurit AND avi NOT at home
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.avi_note8,device_tracker.iphone_nurit
        to: 'not_home'
        for:
          minutes: 1
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.avi_note8
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.iphone_nurit
          state: 'not_home'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.sh20_pow