#################################################################
#                                                               #
#                            Zones                              #
#                                                               #
#################################################################

- name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude 
  radius: 150
  icon: mdi:worker
  
- name: Nurit Work
  latitude: !secret nurit_work_latitude
  longitude: !secret nurit_work_longitude 
  radius: 150
  icon: mdi:human-female 

- name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude  
  radius: 150
  icon: mdi:account-multiple

- name: Mall
  latitude: !secret mall_latitude
  longitude: !secret mall_longitude  
  radius: 150
  icon: mdi:shopping